package configurationtool.view;

import configurationtool.model.Difficulty;
import org.omg.CORBA.DynAnyPackage.InvalidValue;

/**
 *
 * @author halzate93
 */
public class DifficultyPanel extends javax.swing.JPanel {
    private Difficulty difficulty;
    
    /**
     * Creates new form DifficultyPanel
     */
    public DifficultyPanel(Difficulty difficulty) {
        initComponents();
        setDifficulty(difficulty);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ftfNodeCount = new javax.swing.JFormattedTextField();
        ftfErrorMargin = new javax.swing.JFormattedTextField();
        ftfDimensionX = new javax.swing.JFormattedTextField();
        ftfDimensionY = new javax.swing.JFormattedTextField();
        ftfTime = new javax.swing.JFormattedTextField();

        setBorder(null);

        jLabel1.setText("Número de nodos");

        jLabel4.setText("Dimensiones");

        jLabel3.setText("Margen de error");

        jLabel2.setText("Tiempo");

        ftfNodeCount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        ftfNodeCount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ftfNodeCountPropertyChange(evt);
            }
        });

        ftfErrorMargin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ftfErrorMargin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ftfErrorMarginPropertyChange(evt);
            }
        });

        ftfDimensionX.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftfDimensionX.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ftfDimensionXPropertyChange(evt);
            }
        });

        ftfDimensionY.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftfDimensionY.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ftfDimensionYPropertyChange(evt);
            }
        });

        ftfTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftfTime.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ftfTimePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ftfNodeCount)
                    .addComponent(ftfErrorMargin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ftfDimensionX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfDimensionY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ftfTime))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftfNodeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ftfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftfErrorMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftfDimensionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfDimensionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ftfNodeCountPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ftfNodeCountPropertyChange
        try{
            difficulty.setNodeCount(((Number)ftfNodeCount.getValue()).intValue());
        }catch(InvalidValue ex){
            ftfNodeCount.setValue(difficulty.getNodeCount());
        }
    }//GEN-LAST:event_ftfNodeCountPropertyChange

    private void ftfErrorMarginPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ftfErrorMarginPropertyChange
        try{
            difficulty.setErrorMargin(((Number)ftfErrorMargin.getValue()).floatValue());
        }catch(InvalidValue ex){
            ftfErrorMargin.setValue(difficulty.getErrorMargin());
        }
    }//GEN-LAST:event_ftfErrorMarginPropertyChange

    private void ftfDimensionXPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ftfDimensionXPropertyChange
        try{
            difficulty.setDimensionsX(((Number)ftfDimensionX.getValue()).intValue());
        }catch(InvalidValue ex){
            ftfDimensionX.setValue(difficulty.getDimensions().getX());
        }
    }//GEN-LAST:event_ftfDimensionXPropertyChange

    private void ftfDimensionYPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ftfDimensionYPropertyChange
        try{
            difficulty.setDimensionsY(((Number)ftfDimensionY.getValue()).intValue());
        }catch(InvalidValue ex){
            ftfDimensionY.setValue(difficulty.getDimensions().getY());
        }
    }//GEN-LAST:event_ftfDimensionYPropertyChange

    private void ftfTimePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ftfTimePropertyChange
        try{
            difficulty.setTime(((Number)ftfTime.getValue()).intValue());
        }catch(InvalidValue ex){
            ftfTime.setValue(difficulty.getTime());
        }
    }//GEN-LAST:event_ftfTimePropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftfDimensionX;
    private javax.swing.JFormattedTextField ftfDimensionY;
    private javax.swing.JFormattedTextField ftfErrorMargin;
    private javax.swing.JFormattedTextField ftfNodeCount;
    private javax.swing.JFormattedTextField ftfTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    //TODO -- Cambiar los valores del POJO segun los cambios en el panel
    
    public final void setDifficulty(Difficulty difficulty){
        this.difficulty = difficulty;
        ftfNodeCount.setValue(difficulty.getNodeCount());
        ftfTime.setValue(difficulty.getTime());
        ftfErrorMargin.setValue(difficulty.getErrorMargin());
        ftfDimensionX.setValue((int)difficulty.getDimensions().x);
        ftfDimensionY.setValue((int)difficulty.getDimensions().y);
    }
    
    public Difficulty getdifficulty(){
        return difficulty;
    }
            
}
